version: '3'

services:
  hadoop-namenode:
    image: 'uhopper/hadoop-namenode'
    hostname: hadoop-namenode
    ports:
      - "8020:8020"
      - '50070:50070'
    environment:
      - CLUSTER_NAME=hadoop-sandbox
      - HDFS_CONF_dfs_replication=1
    volumes:
      - "./hadoop-dfs-name:/hadoop/dfs/name"

  hadoop-datanode:
    image: "uhopper/hadoop-datanode"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
      - CLUSTER_NAME=hadoop-sandbox
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - "hadoop-namenode"
    volumes:
      - "./hadoop-dfs-data:/hadoop/dfs/data"

networks:
    default:
        external:
            name: ewg-cluster